### PR TITLE
CO-1053 prepare repo for Opendoor code development

### PR DESCRIPTION
**Pull request by missmaggiemo**
* Update README with installation instructions
* Add CODEOWNERS
* Add .tool-versions for the /serverless directory

### CODE REVIEW

**Review by william-zhuang-od — COMMENTED** [review]
This is a fork but do we want to move this into the code repo so that it'll work with our pipelines? At some point we'll have to put the functions in there since all of the functions must be deployed together.

**Comment by missmaggiemo** [comment]
> At some point we'll have to put the functions in there since all of the functions must be deployed together.

That was always our understanding. However, I think we can create a new functions service (see [Twilio admin UI](https://www.twilio.com/console/functions/overview/services) and the [docs](https://www.twilio.com/docs/runtime/functions-assets-api/api/service)) to deploy these functions so that they won't conflict with our existing functions. I wrote some more notes in [this ticket](https://opendoor.atlassian.net/browse/CO-1236).

**Comment by missmaggiemo** [comment]
Also, it would be much more challenging to keep this plugin up to date with the upstream version if we merge this plugin into the opendoor/code repo. As far as I can tell, this plugin is still actively being developed, and I'd like to be able to pull in those updates. If this works out, it might be a better road for plugins that we want to fork and keep up to date with upstream.

**Review by william-zhuang-od — APPROVED** [review]
Looks good to me

**Pull request merged**
